development:
  adapter: postgresql
  encoding: unicode
  database: two_factor_authentication_db
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432
  
test:
  adapter: postgresql
  encoding: unicode
  database: two_factor_authentication_db_test
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432